version: '3'

volumes:
  logs:
  contacts:

services:
  bot:
    container_name: FAQ_BOT
    image: pytem/faq_tg_bot
    env_file: .env
    volumes:
      - logs:/app/logs
      - contacts:/app/contacts
    restart: always
    command: sh -c "python main.py"
